/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as TechnologyRouteImport } from './routes/technology'
import { Route as RollARackGutterLikeRackingSystemCollectsRainwaterFallingOnSolarArraysRouteImport } from './routes/roll-a-rack-gutter-like-racking-system-collects-rainwater-falling-on-solar-arrays'
import { Route as InTheNewsRouteImport } from './routes/in-the-news'
import { Route as AnnouncingRollARackRouteImport } from './routes/announcing-roll-a-rack'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as VideosIndexRouteImport } from './routes/videos/index'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as VideosInsiderollARackRouteImport } from './routes/videos/insideroll-a-rack'
import { Route as VideosFeavideoRouteImport } from './routes/videos/feavideo'
import { Route as MarketingTermsRouteImport } from './routes/_marketing/terms'
import { Route as MarketingTeamRouteImport } from './routes/_marketing/team'
import { Route as MarketingPrivacyRouteImport } from './routes/_marketing/privacy'
import { Route as MarketingPartnersRouteImport } from './routes/_marketing/partners'
import { Route as MarketingLandfillSolarRouteImport } from './routes/_marketing/landfill-solar'
import { Route as MarketingInstallationsRouteImport } from './routes/_marketing/installations'
import { Route as MarketingForInstallersRouteImport } from './routes/_marketing/for-installers'
import { Route as MarketingEdpPilotRouteImport } from './routes/_marketing/edp-pilot'
import { Route as MarketingContactRouteImport } from './routes/_marketing/contact'
import { Route as MarketingAboutRouteImport } from './routes/_marketing/about'

const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnologyRoute = TechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => rootRouteImport,
} as any)
const RollARackGutterLikeRackingSystemCollectsRainwaterFallingOnSolarArraysRoute =
  RollARackGutterLikeRackingSystemCollectsRainwaterFallingOnSolarArraysRouteImport.update(
    {
      id: '/roll-a-rack-gutter-like-racking-system-collects-rainwater-falling-on-solar-arrays',
      path: '/roll-a-rack-gutter-like-racking-system-collects-rainwater-falling-on-solar-arrays',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const InTheNewsRoute = InTheNewsRouteImport.update({
  id: '/in-the-news',
  path: '/in-the-news',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncingRollARackRoute = AnnouncingRollARackRouteImport.update({
  id: '/announcing-roll-a-rack',
  path: '/announcing-roll-a-rack',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosIndexRoute = VideosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VideosRoute,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const VideosInsiderollARackRoute = VideosInsiderollARackRouteImport.update({
  id: '/insideroll-a-rack',
  path: '/insideroll-a-rack',
  getParentRoute: () => VideosRoute,
} as any)
const VideosFeavideoRoute = VideosFeavideoRouteImport.update({
  id: '/feavideo',
  path: '/feavideo',
  getParentRoute: () => VideosRoute,
} as any)
const MarketingTermsRoute = MarketingTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingTeamRoute = MarketingTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingPrivacyRoute = MarketingPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingPartnersRoute = MarketingPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingLandfillSolarRoute = MarketingLandfillSolarRouteImport.update({
  id: '/landfill-solar',
  path: '/landfill-solar',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingInstallationsRoute = MarketingInstallationsRouteImport.update({
  id: '/installations',
  path: '/installations',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingForInstallersRoute = MarketingForInstallersRouteImport.update({
  id: '/for-installers',
  path: '/for-installers',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingEdpPilotRoute = MarketingEdpPilotRouteImport.update({
  id: '/edp-pilot',
  path: '/edp-pilot',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingContactRoute = MarketingContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingAboutRoute = MarketingAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MarketingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/announcing-roll-a-rack': typeof AnnouncingRollARackRoute
  '/in-the-news': typeof InTheNewsRoute
  '/roll-a-rack-gutter-like-racking-system-collects-rainwater-falling-on-solar-arrays': typeof RollARackGutterLikeRackingSystemCollectsRainwaterFallingOnSolarArraysRoute
  '/technology': typeof TechnologyRoute
  '/videos': typeof VideosRouteWithChildren
  '/about': typeof MarketingAboutRoute
  '/contact': typeof MarketingContactRoute
  '/edp-pilot': typeof MarketingEdpPilotRoute
  '/for-installers': typeof MarketingForInstallersRoute
  '/installations': typeof MarketingInstallationsRoute
  '/landfill-solar': typeof MarketingLandfillSolarRoute
  '/partners': typeof MarketingPartnersRoute
  '/privacy': typeof MarketingPrivacyRoute
  '/team': typeof MarketingTeamRoute
  '/terms': typeof MarketingTermsRoute
  '/videos/feavideo': typeof VideosFeavideoRoute
  '/videos/insideroll-a-rack': typeof VideosInsiderollARackRoute
  '/videos/': typeof VideosIndexRoute
}
export interface FileRoutesByTo {
  '/announcing-roll-a-rack': typeof AnnouncingRollARackRoute
  '/in-the-news': typeof InTheNewsRoute
  '/roll-a-rack-gutter-like-racking-system-collects-rainwater-falling-on-solar-arrays': typeof RollARackGutterLikeRackingSystemCollectsRainwaterFallingOnSolarArraysRoute
  '/technology': typeof TechnologyRoute
  '/about': typeof MarketingAboutRoute
  '/contact': typeof MarketingContactRoute
  '/edp-pilot': typeof MarketingEdpPilotRoute
  '/for-installers': typeof MarketingForInstallersRoute
  '/installations': typeof MarketingInstallationsRoute
  '/landfill-solar': typeof MarketingLandfillSolarRoute
  '/partners': typeof MarketingPartnersRoute
  '/privacy': typeof MarketingPrivacyRoute
  '/team': typeof MarketingTeamRoute
  '/terms': typeof MarketingTermsRoute
  '/videos/feavideo': typeof VideosFeavideoRoute
  '/videos/insideroll-a-rack': typeof VideosInsiderollARackRoute
  '/': typeof MarketingIndexRoute
  '/videos': typeof VideosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_marketing': typeof MarketingRouteWithChildren
  '/announcing-roll-a-rack': typeof AnnouncingRollARackRoute
  '/in-the-news': typeof InTheNewsRoute
  '/roll-a-rack-gutter-like-racking-system-collects-rainwater-falling-on-solar-arrays': typeof RollARackGutterLikeRackingSystemCollectsRainwaterFallingOnSolarArraysRoute
  '/technology': typeof TechnologyRoute
  '/videos': typeof VideosRouteWithChildren
  '/_marketing/about': typeof MarketingAboutRoute
  '/_marketing/contact': typeof MarketingContactRoute
  '/_marketing/edp-pilot': typeof MarketingEdpPilotRoute
  '/_marketing/for-installers': typeof MarketingForInstallersRoute
  '/_marketing/installations': typeof MarketingInstallationsRoute
  '/_marketing/landfill-solar': typeof MarketingLandfillSolarRoute
  '/_marketing/partners': typeof MarketingPartnersRoute
  '/_marketing/privacy': typeof MarketingPrivacyRoute
  '/_marketing/team': typeof MarketingTeamRoute
  '/_marketing/terms': typeof MarketingTermsRoute
  '/videos/feavideo': typeof VideosFeavideoRoute
  '/videos/insideroll-a-rack': typeof VideosInsiderollARackRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/videos/': typeof VideosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/announcing-roll-a-rack'
    | '/in-the-news'
    | '/roll-a-rack-gutter-like-racking-system-collects-rainwater-falling-on-solar-arrays'
    | '/technology'
    | '/videos'
    | '/about'
    | '/contact'
    | '/edp-pilot'
    | '/for-installers'
    | '/installations'
    | '/landfill-solar'
    | '/partners'
    | '/privacy'
    | '/team'
    | '/terms'
    | '/videos/feavideo'
    | '/videos/insideroll-a-rack'
    | '/videos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/announcing-roll-a-rack'
    | '/in-the-news'
    | '/roll-a-rack-gutter-like-racking-system-collects-rainwater-falling-on-solar-arrays'
    | '/technology'
    | '/about'
    | '/contact'
    | '/edp-pilot'
    | '/for-installers'
    | '/installations'
    | '/landfill-solar'
    | '/partners'
    | '/privacy'
    | '/team'
    | '/terms'
    | '/videos/feavideo'
    | '/videos/insideroll-a-rack'
    | '/'
    | '/videos'
  id:
    | '__root__'
    | '/_marketing'
    | '/announcing-roll-a-rack'
    | '/in-the-news'
    | '/roll-a-rack-gutter-like-racking-system-collects-rainwater-falling-on-solar-arrays'
    | '/technology'
    | '/videos'
    | '/_marketing/about'
    | '/_marketing/contact'
    | '/_marketing/edp-pilot'
    | '/_marketing/for-installers'
    | '/_marketing/installations'
    | '/_marketing/landfill-solar'
    | '/_marketing/partners'
    | '/_marketing/privacy'
    | '/_marketing/team'
    | '/_marketing/terms'
    | '/videos/feavideo'
    | '/videos/insideroll-a-rack'
    | '/_marketing/'
    | '/videos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MarketingRoute: typeof MarketingRouteWithChildren
  AnnouncingRollARackRoute: typeof AnnouncingRollARackRoute
  InTheNewsRoute: typeof InTheNewsRoute
  RollARackGutterLikeRackingSystemCollectsRainwaterFallingOnSolarArraysRoute: typeof RollARackGutterLikeRackingSystemCollectsRainwaterFallingOnSolarArraysRoute
  TechnologyRoute: typeof TechnologyRoute
  VideosRoute: typeof VideosRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technology': {
      id: '/technology'
      path: '/technology'
      fullPath: '/technology'
      preLoaderRoute: typeof TechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roll-a-rack-gutter-like-racking-system-collects-rainwater-falling-on-solar-arrays': {
      id: '/roll-a-rack-gutter-like-racking-system-collects-rainwater-falling-on-solar-arrays'
      path: '/roll-a-rack-gutter-like-racking-system-collects-rainwater-falling-on-solar-arrays'
      fullPath: '/roll-a-rack-gutter-like-racking-system-collects-rainwater-falling-on-solar-arrays'
      preLoaderRoute: typeof RollARackGutterLikeRackingSystemCollectsRainwaterFallingOnSolarArraysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/in-the-news': {
      id: '/in-the-news'
      path: '/in-the-news'
      fullPath: '/in-the-news'
      preLoaderRoute: typeof InTheNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcing-roll-a-rack': {
      id: '/announcing-roll-a-rack'
      path: '/announcing-roll-a-rack'
      fullPath: '/announcing-roll-a-rack'
      preLoaderRoute: typeof AnnouncingRollARackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/': {
      id: '/videos/'
      path: '/'
      fullPath: '/videos/'
      preLoaderRoute: typeof VideosIndexRouteImport
      parentRoute: typeof VideosRoute
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/videos/insideroll-a-rack': {
      id: '/videos/insideroll-a-rack'
      path: '/insideroll-a-rack'
      fullPath: '/videos/insideroll-a-rack'
      preLoaderRoute: typeof VideosInsiderollARackRouteImport
      parentRoute: typeof VideosRoute
    }
    '/videos/feavideo': {
      id: '/videos/feavideo'
      path: '/feavideo'
      fullPath: '/videos/feavideo'
      preLoaderRoute: typeof VideosFeavideoRouteImport
      parentRoute: typeof VideosRoute
    }
    '/_marketing/terms': {
      id: '/_marketing/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof MarketingTermsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/team': {
      id: '/_marketing/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof MarketingTeamRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/privacy': {
      id: '/_marketing/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof MarketingPrivacyRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/partners': {
      id: '/_marketing/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof MarketingPartnersRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/landfill-solar': {
      id: '/_marketing/landfill-solar'
      path: '/landfill-solar'
      fullPath: '/landfill-solar'
      preLoaderRoute: typeof MarketingLandfillSolarRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/installations': {
      id: '/_marketing/installations'
      path: '/installations'
      fullPath: '/installations'
      preLoaderRoute: typeof MarketingInstallationsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/for-installers': {
      id: '/_marketing/for-installers'
      path: '/for-installers'
      fullPath: '/for-installers'
      preLoaderRoute: typeof MarketingForInstallersRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/edp-pilot': {
      id: '/_marketing/edp-pilot'
      path: '/edp-pilot'
      fullPath: '/edp-pilot'
      preLoaderRoute: typeof MarketingEdpPilotRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/contact': {
      id: '/_marketing/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof MarketingContactRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/about': {
      id: '/_marketing/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MarketingAboutRouteImport
      parentRoute: typeof MarketingRoute
    }
  }
}

interface MarketingRouteChildren {
  MarketingAboutRoute: typeof MarketingAboutRoute
  MarketingContactRoute: typeof MarketingContactRoute
  MarketingEdpPilotRoute: typeof MarketingEdpPilotRoute
  MarketingForInstallersRoute: typeof MarketingForInstallersRoute
  MarketingInstallationsRoute: typeof MarketingInstallationsRoute
  MarketingLandfillSolarRoute: typeof MarketingLandfillSolarRoute
  MarketingPartnersRoute: typeof MarketingPartnersRoute
  MarketingPrivacyRoute: typeof MarketingPrivacyRoute
  MarketingTeamRoute: typeof MarketingTeamRoute
  MarketingTermsRoute: typeof MarketingTermsRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingAboutRoute: MarketingAboutRoute,
  MarketingContactRoute: MarketingContactRoute,
  MarketingEdpPilotRoute: MarketingEdpPilotRoute,
  MarketingForInstallersRoute: MarketingForInstallersRoute,
  MarketingInstallationsRoute: MarketingInstallationsRoute,
  MarketingLandfillSolarRoute: MarketingLandfillSolarRoute,
  MarketingPartnersRoute: MarketingPartnersRoute,
  MarketingPrivacyRoute: MarketingPrivacyRoute,
  MarketingTeamRoute: MarketingTeamRoute,
  MarketingTermsRoute: MarketingTermsRoute,
  MarketingIndexRoute: MarketingIndexRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

interface VideosRouteChildren {
  VideosFeavideoRoute: typeof VideosFeavideoRoute
  VideosInsiderollARackRoute: typeof VideosInsiderollARackRoute
  VideosIndexRoute: typeof VideosIndexRoute
}

const VideosRouteChildren: VideosRouteChildren = {
  VideosFeavideoRoute: VideosFeavideoRoute,
  VideosInsiderollARackRoute: VideosInsiderollARackRoute,
  VideosIndexRoute: VideosIndexRoute,
}

const VideosRouteWithChildren =
  VideosRoute._addFileChildren(VideosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MarketingRoute: MarketingRouteWithChildren,
  AnnouncingRollARackRoute: AnnouncingRollARackRoute,
  InTheNewsRoute: InTheNewsRoute,
  RollARackGutterLikeRackingSystemCollectsRainwaterFallingOnSolarArraysRoute:
    RollARackGutterLikeRackingSystemCollectsRainwaterFallingOnSolarArraysRoute,
  TechnologyRoute: TechnologyRoute,
  VideosRoute: VideosRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
