/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as MarketingTermsRouteImport } from './routes/_marketing/terms'
import { Route as MarketingTeamRouteImport } from './routes/_marketing/team'
import { Route as MarketingPrivacyRouteImport } from './routes/_marketing/privacy'
import { Route as MarketingInstallationsRouteImport } from './routes/_marketing/installations'
import { Route as MarketingForInvestorsRouteImport } from './routes/_marketing/for-investors'
import { Route as MarketingForInstallersRouteImport } from './routes/_marketing/for-installers'
import { Route as MarketingContactRouteImport } from './routes/_marketing/contact'
import { Route as MarketingAboutRouteImport } from './routes/_marketing/about'

const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingTermsRoute = MarketingTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingTeamRoute = MarketingTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingPrivacyRoute = MarketingPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingInstallationsRoute = MarketingInstallationsRouteImport.update({
  id: '/installations',
  path: '/installations',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingForInvestorsRoute = MarketingForInvestorsRouteImport.update({
  id: '/for-investors',
  path: '/for-investors',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingForInstallersRoute = MarketingForInstallersRouteImport.update({
  id: '/for-installers',
  path: '/for-installers',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingContactRoute = MarketingContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingAboutRoute = MarketingAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MarketingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/about': typeof MarketingAboutRoute
  '/contact': typeof MarketingContactRoute
  '/for-installers': typeof MarketingForInstallersRoute
  '/for-investors': typeof MarketingForInvestorsRoute
  '/installations': typeof MarketingInstallationsRoute
  '/privacy': typeof MarketingPrivacyRoute
  '/team': typeof MarketingTeamRoute
  '/terms': typeof MarketingTermsRoute
}
export interface FileRoutesByTo {
  '/about': typeof MarketingAboutRoute
  '/contact': typeof MarketingContactRoute
  '/for-installers': typeof MarketingForInstallersRoute
  '/for-investors': typeof MarketingForInvestorsRoute
  '/installations': typeof MarketingInstallationsRoute
  '/privacy': typeof MarketingPrivacyRoute
  '/team': typeof MarketingTeamRoute
  '/terms': typeof MarketingTermsRoute
  '/': typeof MarketingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_marketing': typeof MarketingRouteWithChildren
  '/_marketing/about': typeof MarketingAboutRoute
  '/_marketing/contact': typeof MarketingContactRoute
  '/_marketing/for-installers': typeof MarketingForInstallersRoute
  '/_marketing/for-investors': typeof MarketingForInvestorsRoute
  '/_marketing/installations': typeof MarketingInstallationsRoute
  '/_marketing/privacy': typeof MarketingPrivacyRoute
  '/_marketing/team': typeof MarketingTeamRoute
  '/_marketing/terms': typeof MarketingTermsRoute
  '/_marketing/': typeof MarketingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/for-installers'
    | '/for-investors'
    | '/installations'
    | '/privacy'
    | '/team'
    | '/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/contact'
    | '/for-installers'
    | '/for-investors'
    | '/installations'
    | '/privacy'
    | '/team'
    | '/terms'
    | '/'
  id:
    | '__root__'
    | '/_marketing'
    | '/_marketing/about'
    | '/_marketing/contact'
    | '/_marketing/for-installers'
    | '/_marketing/for-investors'
    | '/_marketing/installations'
    | '/_marketing/privacy'
    | '/_marketing/team'
    | '/_marketing/terms'
    | '/_marketing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MarketingRoute: typeof MarketingRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/terms': {
      id: '/_marketing/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof MarketingTermsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/team': {
      id: '/_marketing/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof MarketingTeamRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/privacy': {
      id: '/_marketing/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof MarketingPrivacyRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/installations': {
      id: '/_marketing/installations'
      path: '/installations'
      fullPath: '/installations'
      preLoaderRoute: typeof MarketingInstallationsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/for-investors': {
      id: '/_marketing/for-investors'
      path: '/for-investors'
      fullPath: '/for-investors'
      preLoaderRoute: typeof MarketingForInvestorsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/for-installers': {
      id: '/_marketing/for-installers'
      path: '/for-installers'
      fullPath: '/for-installers'
      preLoaderRoute: typeof MarketingForInstallersRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/contact': {
      id: '/_marketing/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof MarketingContactRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/about': {
      id: '/_marketing/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MarketingAboutRouteImport
      parentRoute: typeof MarketingRoute
    }
  }
}

interface MarketingRouteChildren {
  MarketingAboutRoute: typeof MarketingAboutRoute
  MarketingContactRoute: typeof MarketingContactRoute
  MarketingForInstallersRoute: typeof MarketingForInstallersRoute
  MarketingForInvestorsRoute: typeof MarketingForInvestorsRoute
  MarketingInstallationsRoute: typeof MarketingInstallationsRoute
  MarketingPrivacyRoute: typeof MarketingPrivacyRoute
  MarketingTeamRoute: typeof MarketingTeamRoute
  MarketingTermsRoute: typeof MarketingTermsRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingAboutRoute: MarketingAboutRoute,
  MarketingContactRoute: MarketingContactRoute,
  MarketingForInstallersRoute: MarketingForInstallersRoute,
  MarketingForInvestorsRoute: MarketingForInvestorsRoute,
  MarketingInstallationsRoute: MarketingInstallationsRoute,
  MarketingPrivacyRoute: MarketingPrivacyRoute,
  MarketingTeamRoute: MarketingTeamRoute,
  MarketingTermsRoute: MarketingTermsRoute,
  MarketingIndexRoute: MarketingIndexRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MarketingRoute: MarketingRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
